Add missing include for limits
Without this the following error occurs:

src/graphic_model/engravers/lomse_wedge_engraver.cpp:
  In member function 'lomse::LUnits lomse::WedgeEngraver::determine_default_shape_position_left(bool) const':
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:39: error: 'numeric_limits' is not a member of 'std'
  242 |     constexpr LUnits xMaxValue = std::numeric_limits<LUnits>::max();
      |                                       ^~~~~~~~~~~~~~
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:60: error: expected primary-expression before '>' token
  242 |     constexpr LUnits xMaxValue = std::numeric_limits<LUnits>::max();
      |                                                            ^
src/graphic_model/engravers/lomse_wedge_engraver.cpp:242:66: error: no matching function for call to 'max()'
  242 |     constexpr LUnits xMaxValue = std::numeric_limits<LUnits>::max();
      |                                                             ~~~~~^~